#!/bin/sh -e

tar xf edf489332a36c4e55e768aa58c23372c2b051dc5
cp disable-wxPaintEvent.patch Ishiiruka-edf489332a36c4e55e768aa58c23372c2b051dc5/.
cp fix-fd_set-error.patch Ishiiruka-edf489332a36c4e55e768aa58c23372c2b051dc5/.
cd Ishiiruka-edf489332a36c4e55e768aa58c23372c2b051dc5

for patch in *.patch; do
    patch -p1 < "$patch"
done

mkdir build
cd build

cmake -DCMAKE_INSTALL_PREFIX="/usr" ..

make
make DESTDIR="$1" install
